const voc = [
  { en: "My name is", pt: "chamo–me" },
  { en: "I think", pt: "Acho" },
  { en: "butterfly", pt: "Borboleta" },
  { en: "there is", pt: "Há" },
  { en: "pens", pt: "Canetas" },
  { en: "how many", pt: "Quantas" },
  { en: "Can you", pt: "Pudes" },
  { en: "repeat", pt: "repetir" },
  { en: "no", pt: "Não" },
  { en: "I didn't understand", pt: "Não percebi" },
  { en: "There are 10 pens here", pt: "Aqui há dez canetas" },
  { en: "here", pt: "Aqui" },
  { en: "what is your name", pt: "Como te chames" },
  { en: "how are you", pt: "Como estás" },
  { en: "I am good", pt: "Eu estou bem" },
  { en: "Where do you live", pt: "Onde vives" },
  { en: "where", pt: "Onde" },
  { en: "When is your birthday", pt: "Quando é o teu aniversário" },
  { en: "(how) cool!", pt: "Que fixe" },
  { en: "I think that yes", pt: "Eu acho que sim" },
  { en: "car", pt: "carro" },
  { en: "nice/cool", pt: "giro" },
  { en: "what", pt: "Que" },
  { en: "I have", pt: "Tehno" },
  { en: "people", pt: "Pessoas" },
  { en: "person", pt: "Pessoa" },
  { en: "man", pt: "homem" },
  { en: "woman", pt: "Mulher" },
  { en: "children", pt: "Crianças" },
  { en: "child (male)", pt: "Menino" },
  { en: "child (female)", pt: "Menina" },
  { en: "family", pt: "Familia" },
  { en: "father", pt: "Pai" },
  { en: "mother", pt: "Mãe" },
  { en: "parents", pt: "Pais" },
  { en: "son", pt: "Filho" },
  { en: "daughter", pt: "Filha" },
  { en: "children (in the family)", pt: "Filhos" },
  { en: "brother", pt: "Irmão" },
  { en: "sister", pt: "Irmã" },
  { en: "husbend", pt: "Marido" },
  { en: "friend (male)", pt: "Amigo" },
  { en: "friend (female)", pt: "Amiga" },
  { en: "class", pt: "Aula" },
  { en: "mine (for male)", pt: "O meu" },
  { en: "mine (for female)", pt: "A minha" },
  { en: "Yours (for male)", pt: "O teu" },
  { en: "Yours (for female)", pt: "A tua" },
  { en: "siblings", pt: "irmãos" },
  { en: "(do) you have", pt: "Tens" },
  { en: "How many siblings do you have", pt: "Quantos irmãos tens" },
  { en: "see you later", pt: "Até logo" },
  { en: "see you soon", pt: "Até à próxima" },
  { en: "now", pt: "Agora" },
  { en: "functions (verb)", pt: "funciona" },
  { en: "owner", pt: "Dono" },
  { en: "I am 35 years old", pt: "Eu tenho trinta e cinco anos" },
  { en: "question", pt: "pergunta" },
  { en: "which", pt: "qual" },
  { en: "@ (at sign)", pt: "arroba" },
  { en: "introduction", pt: "Apresentação" },
  { en: "(I) live/reside", pt: "moro" },
  { en: "with", pt: "com" },
  { en: "on/in ??", pt: "num" },
  { en: "apartment", pt: "apartamento" },
  { en: "small", pt: "pequeno" },
  { en: "but", pt: "mas" },
  { en: "(I) like", pt: "gosto" },
  { en: "to receive", pt: "receber" },
  { en: "visitors", pt: "visitas" },
  { en: "If", pt: "Se" },
  { en: "(you) like", pt: "gostas" },
  { en: "cities", pt: "cidades" },
  { en: "big", pt: "grande" },
  { en: "to know", pt: "conhecer" },
  { en: "interesent", pt: "interessante" },
  { en: "for", pt: "para" },
  { en: "for you", pt: "para ti" },
  { en: "with you", pt: "contigo" },
  { en: "also", pt: "Também!" },
  { en: "when", pt: "Quando" },
  { en: "(you) come", pt: "vens" },
  { en: "day", pt: "Dia" },
  { en: "idea", pt: "ideia" },
  { en: "I am", pt: "Estou" },
  { en: "I see", pt: "Estou a ver" },
  { en: "Or", pt: "Ou" },
  { en: "only", pt: "só" },
  { en: "dog", pt: "cãe" },
  { en: "how nice", pt: "Que bom" },
  { en: "teacher (female)", pt: "professora" },
  { en: "history", pt: "História" },
  { en: "geography", pt: "Geografia" },
  { en: "pleasure", pt: "prazer" },
  { en: "(I) use", pt: "uso" },
  { en: "From where", pt: "De onde" },
  { en: "united states", pt: "Estados Unidos" },
  { en: "from", pt: "dos" },
  { en: "movie", pt: "filme" },
  { en: "preferred", pt: "preferido" },
  { en: "how to say", pt: "Como se diz" },
  { en: "dog", pt: "cão" },
  { en: "what is your name", pt: "como se chama" },
  { en: "best", pt: "melhor" },
  { en: "he", pt: "ele" },
  { en: "until", pt: "até" },
  { en: "you", pt: "tu" },
  { en: "week", pt: "semana" },
  { en: "today", pt: "hoje" },
  { en: "tomorrow", pt: "amanhã" },
  { en: "Friday", pt: "sexta–feira" },
  { en: "Saturday", pt: "sábado" },
  { en: "Sunday", pt: "Domigo" },
  { en: "Monday", pt: "Segunda–feira" },
  { en: "Tuesday", pt: "terça–feira" },
  { en: "Wednesday", pt: "quarta–feira" },
  { en: "Thursday", pt: "Quinta–feira" },
  { en: "she", pt: "ela" },
  { en: "we", pt: "Nós" },
  { en: "you (plural)", pt: "vocês" },
  { en: "they (masculine)", pt: "Eles" },
  { en: "they (faminine)", pt: "Elas" },
  { en: "to be", pt: "ser" },
  { en: "(i) work (also as a noun)", pt: "trabalho" },
  { en: "colleagues", pt: "colegas" },
  { en: "good", pt: "bom" },
  { en: "bad", pt: "mau" },
  { en: "new (also: young person)", pt: "novo" },
  { en: "old (also: old person)", pt: "velho" },
  { en: "usual", pt: "comum" },
  { en: "not usual", pt: "pouco comum" },
  { en: "expesnive", pt: "caro" },
  { en: "cheap", pt: "barato" },
  { en: "beautiful", pt: "bonito" },
  { en: "ugly", pt: "feio" },
  { en: "easy", pt: "fácil" },
  { en: "difficult", pt: "difícil" },
  { en: "important", pt: "importante" },
  { en: "not so important", pt: "pouco importante" },
  { en: "interesting", pt: "interessante" },
  { en: "boring / annoying", pt: "chato" },
  { en: "how", pt: "como" },
  { en: "house", pt: "casa" },
  { en: "this (masculine)", pt: "este" },
  { en: "this (feminine)", pt: "esta" },
  { en: "a lot", pt: "muito" },
  { en: "a little", pt: "um pouco" },
  { en: "a bit", pt: "um bocado" },
  { en: "(I) live", pt: "vivo" },
  { en: "(i) speak", pt: "falo" },
  { en: "(i) like", pt: "gosto" },
  { en: "(i) need", pt: "preciso" },
  { en: "close by", pt: "perto" },
  { en: "far", pt: "longe" },
  { en: "sugar", pt: "açúar" },
  { en: "sandwiches", pt: "sanduiches" },
  { en: "Shoes", pt: "Sapatos" },
  { en: "More", pt: "Mais" },
  { en: "Know", pt: "Sei" },
  { en: "Number", pt: "Número" },
  { en: "Number", pt: "Número" },
  { en: "Police", pt: "Polícia" },
  { en: "In this ", pt: "Neste/a" },
  { en: "Exercise", pt: "Excercício" },
  { en: "Exercise", pt: "Excercício" },
  { en: "United states", pt: "Estados unidos" },
  { en: "Exercise", pt: "Excercício" },
  { en: "United states", pt: "Estados unidos" },
  { en: "Also", pt: "Também" },
  { en: "Exercise", pt: "Excercício" },
  { en: "United states", pt: "Estados unidos" },
  { en: "Also", pt: "Também" },
  { en: "Students", pt: "Alunos" },
  { en: "Already", pt: "já" },
  { en: "street", pt: "a rua" },
  { en: "(town) center", pt: "o centro" },
  { en: "shop", pt: "a loja" },
  { en: "shopping mall", pt: "o shopping / o centro commercial" },
  { en: "station", pt: "a estação" },
  { en: "train", pt: "o comboio" },
  { en: "train station", pt: "a estação de comboio" },
  { en: "restaurant", pt: "o restaurante" },
  { en: "company", pt: "a empresa" },
  { en: "school", pt: "a escola" },
  { en: "bus stop", pt: "a paragem de autocarro" },
  { en: "what is that?", pt: "o que é isto?" },
  { en: "(you) know", pt: "sabes" },
  { en: "(i) go", pt: "vou" },
  { en: "(you) go", pt: "vais" },
  { en: "(i) can", pt: "posso" },
  { en: "(you) can", pt: "podes" },
  { en: "(i) want", pt: "quero" },
  { en: "(you) want", pt: "queres" },
  { en: "suitcase", pt: "uma mala" },
  { en: "enough", pt: "suficiente" },
  { en: "thing", pt: "uma coisa" },
  { en: "purse", pt: "a carteira" },
  { en: "snack", pt: "o lanche" },
  { en: "coat", pt: "casaco" },
  { en: "cold", pt: "frio" },
  { en: "to take", pt: "levar" },
  { en: "say it!", pt: "Diz!" },
  { en: "from here", pt: "daqui" },
  { en: "surprise", pt: "surpresa" },
  { en: "so", pt: "então" },
  { en: "salary", pt: "salário" },
  { en: "sandwiches", pt: "sandes" },
  { en: "because / why", pt: "porque" },
  { en: "to go", pt: "ir" },
  { en: "screen", pt: "Ecrã" },
  { en: "keyboard", pt: "Teclado" },
  { en: "mouse", pt: "Rato" },
  { en: "type", pt: "tipo" },
  { en: "in that", pt: "nessa" },
  { en: "working", pt: "a trabalhar" },
  { en: "bag", pt: "o saco" },
  { en: "to help", pt: "ajudar" },
  { en: "living room", pt: "sala" },
  { en: "office", pt: "escritório" },
  { en: "famous", pt: "famoso/a" },
  { en: "for sure", pt: "com certsa" },
  { en: "toothpick", pt: "palito" },
  { en: "joyfull", pt: "alegre" },
  { en: "happy", pt: "felix" },
  { en: "on top / above", pt: "em cima" },
  { en: "sad", pt: "triste" },
  { en: "tired", pt: "cansado" },
  { en: "cold", pt: "com frio" },
  { en: "warm", pt: "com calor" },
  { en: "hungry", pt: "com fome" },
  { en: "thirsty", pt: "com sede" },
  { en: "minus / less", pt: "menos" },
  { en: "give or take", pt: "mais ou menos" },
  { en: "rice", pt: "arroz" },
  { en: "salad", pt: "salada" },
  { en: "times (2 X 7)", pt: "vezes" },
  { en: "future", pt: "futuro" },
  { en: "similar", pt: "parecida" },
  { en: "music", pt: "música" },
  { en: "delay", pt: "demora" },
  { en: "prepare", pt: "preparar" },
  { en: "married", pt: "casado" },
  { en: "to buy", pt: "comprar" },
  { en: "for", pt: "para" },
  { en: "to sleep", pt: "dormir" },
  { en: "language", pt: "língua" },
  { en: "a little", pt: "bocadinho" },
  { en: "how much", pt: "quanto" },
  { en: "to eat", pt: "comer" },
  { en: "allow me", pt: "deixa-me" },
  { en: "to see", pt: "ver" },
  { en: "address", pt: "morada" },
  { en: "here it is", pt: "aqui tem" },
  { en: "time", pt: "tempo" },
  { en: "how long it takes?", pt: "quanto tempo demora?" },
  { en: "great", pt: "Ótimo" },
  { en: "driver", pt: "Motorista" },
  { en: "first", pt: "primeira/o" },
  { en: "for the first time", pt: "pela primeira vez" },
  { en: "time/turn", pt: "vez" },
  { en: "adventures", pt: "aventuras" },
  { en: "place", pt: "lugar" },
  { en: "profession", pt: "profissão" },
  { en: "lawyer", pt: "advogado" },
  { en: "serriously", pt: "a sério" },
  { en: "still", pt: "ainda" },
  { en: "to study", pt: "estudar" },
  { en: "some", pt: "uns / algumas" },
  { en: "site", pt: "sítio" },
  { en: "exactly", pt: "Exatamente" },
  { en: "beginning", pt: "início" },
  { en: "quarter", pt: "um quarto" },
  { en: "half", pt: "meia" },
  { en: "morning", pt: "a manhã" },
  { en: "afternoon", pt: "a tarde" },
  { en: "night", pt: "a noite" },
  { en: "hour", pt: "hora" },
  { en: "minute", pt: "minuto" },
  { en: "noon", pt: "meio-dia" },
  { en: "midnight", pt: "meia-noita" },
  { en: "almost", pt: "quase" },
  { en: "appear", pt: "aparece" },
  { en: "listen", pt: "ouvir" },
  { en: "at least", pt: "finalmente" },
  { en: "money", pt: "dinheiro" },
  { en: "clock", pt: "relógio" },
  { en: "back (to)", pt: "de volta" },
  { en: "another", pt: "outra" },
  { en: "too much", pt: "demais" },
  { en: "to arrive", pt: "chegar" },
  { en: "excellent", pt: "Ótimo" },
  { en: "elevator", pt: "o elevador" },
  { en: "well/because", pt: "pois" },
  { en: "without", pt: "sem" },
  { en: "welcome", pt: "Bem-vinda" },
  { en: "reception", pt: "recepção" },
  { en: "kitchen", pt: "cozinha" },
  { en: "alright", pt: "está bem" },
  { en: "refrigirator", pt: "frigorífico" },
  { en: "to write", pt: "escrever" },
  { en: "during", pt: "durante" },
  { en: "beside", pt: "ao lado" },
  { en: "bathroom", pt: "casa de banho" },
  { en: "bedroom", pt: "quarto" },
  { en: "garage", pt: "garagem" },
  { en: "any", pt: "algum/a" },
  { en: "something", pt: "alguma coise" },
  { en: "none", pt: "nenhum" },
  { en: "sofa", pt: "o sofá" },
  { en: "table", pt: "a mesa" },
  { en: "building", pt: "o prédio" },
  { en: "chair", pt: "a cadeira" },
  { en: "air conditioning", pt: "o ar condicionado" },
  { en: "door", pt: "a porta" },
  { en: "floor", pt: "o chão" },
  { en: "wardrobe", pt: "o armário" },
  { en: "stairs", pt: "as escadas" },
  { en: "computer", pt: "o computador" },
  { en: "window", pt: "a janela" },
  { en: "mobile phone", pt: "telemóvel" },
  { en: "about", pt: "sobre" },
  { en: "over here", pt: "Cá" },
  { en: "problem", pt: "problema" },
];

export default voc;
